shopslot_lakehouse:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('DBT_SPARK_HOST', 'spark-thrift') }}"
      port: 10000
      user: dbt
      schema: silver_dbt
      threads: 2
      connect_retries: 5
      connect_timeout: 60
      retry_all: true
